=== MaayanLab/appyter-catalog/schema/appyter-validator.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "properties": {
    "$schema": {
      "description": "A reference to this schema",
      "type": "string",
      "enum": [
        "https://raw.githubusercontent.com/MaayanLab/appyter-catalog/master/schema/appyter-validator.json"
      ]
    },
    "name": {
      "description": "Slug name of this appyter (same as directory, used as url location)",
      "type": "string",
      "pattern": "^[a-zA-Z][a-zA-Z0-9_]*$"
    },
    "title": {
      "description": "Appyter title",
      "type": "string"
    },
    "version": {
      "description": "Semver version",
      "type": "string",
      "format": "regex",
      "pattern": "^[0-9]+\\.[0-9]+\\.[0-9]+$"
    },
    "description": {
      "description": "A short description of the appyter",
      "type": "string",
      "maxLength": 150
    },
    "authors": {
      "description": "A list of authors who contributed to the appyter",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "description": "The name of the author",
            "type": "string"
          },
          "email": {
            "description": "The email of the author",
            "type": "string",
            "format": "email"
          }
        }
      }
    },
    "image": {
      "description": "A relative path (preferred) or url to a thumbnail for the appyter. Size: 1280x720",
      "type": "string"
    },
    "url": {
      "description": "A url to the source code or website of the appyter",
      "type": "string",
      "format": "url"
    },
    "tags": {
      "description": "A set of tags describing the appyter",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "license": {
      "description": "A license identified by https://spdx.org/licenses/",
      "type": "string"
    },
    "public": {
      "description": "Whether or not this should be visible on the catalog (defaults to true)",
      "type": "boolean"
    },
    "appyter": {
      "description": "Appyter information and configuration",
      "type": "object",
      "properties": {
        "file": {
          "description": "The appyter file relative to this directory",
          "type": "string"
        },
        "profile": {
          "description": "The pre-made profile to base the appyter off of",
          "type": "string"
        },
        "extras": {
          "description": "Any extras to enable in your appyter",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "file"
      ]
    }
  },
  "required": [
    "$schema",
    "name",
    "title",
    "version",
    "description",
    "authors",
    "license",
    "appyter"
  ]
}

=== MaayanLab/appyter-catalog/appyters/PHGKB_Harmonizome_ETL/appyter.json
{
  "$schema": "https://raw.githubusercontent.com/MaayanLab/appyter-catalog/master/schema/appyter-validator.json",
  "name": "PHGKB_Harmonizome_ETL",
  "title": "Harmonizome ETL: Public Health Genomics and Precision Health Knowledge Base",
  "version": "0.1.2",
  "description": "An appyter to process data from the Public Health Genomics and Precision Health Knowledge Base for the Harmonizome.",
  "image": "ETL_Logo.png",
  "authors": [
    {
      "name": "Charles R. Dai",
      "email": "charles.r.dai@gmail.com"
    }
  ],
  "url": "https://github.com/MaayanLab/Harmonizome-Data-Processing-Appyters",
  "tags": [
    "Harmonizome",
    "Harmonizome ETL Script",
    "PHGKB"
  ],
  "license": "MIT",
  "appyter": {
    "file": "PHGKB.ipynb",
    "profile": "biojupies"
  }
}

=== MaayanLab/appyter-catalog/appyters/STITCH_Drugmonizome_ETL/appyter.json
{
  "$schema": "https://raw.githubusercontent.com/MaayanLab/appyter-catalog/master/schema/appyter-validator.json",
  "name": "STITCH_Drugmonizome_ETL",
  "title": "Drugmonizome ETL: STITCH",
  "version": "0.0.2",
  "description": "An appyter to process drug-protein associations from STITCH.",
  "image": "Drugmonizome_ETL.png",
  "authors": [
    {
      "name": "Eryk Kropiwnicki",
      "email": "eryk.kropiwnicki@icahn.mssm.edu"
    }
  ],
  "url": "https://github.com/MaayanLab/Drugmonizome-Data-Processing-Appyters",
  "tags": [
    "Drugmonizome",
    "ETL Script",
    "STITCH"
  ],
  "license": "MIT",
  "appyter": {
    "file": "STITCH.ipynb",
    "profile": "biojupies"
  }
}

=== MaayanLab/appyter-catalog/appyters/Gene-Aging-Trends-Appyter/appyter.json
{
    "$schema": "https://raw.githubusercontent.com/MaayanLab/appyter-catalog/master/schema/appyter-validator.json",
    "name":"Gene-Age-Trends-Appyter",
    "title": "Gene Expression vs Age Plot Generator",
    "version": "0.0.1",
    "description": "An appyter that creates bar charts to visualize KINOMEscan and TAS vectors data from HMS LINCS.",
    "authors": [
      {
        "name": "Tahmid Ahamed",
        "email": "ahamedt@wharton.upenn.edu"
      }
    ],
    "url": "https://github.com/MaayanLab/appyter-catalog",
    "tags": [
      "Gene Expression, Age, Mouse,Human"
    ],
    "license": "Apache-2.0",
    "appyter": {
      "file": "Age_Gene_Appyter.ipynb",
      "profile": "biojupies"
    }
  }

=== MaayanLab/appyter-catalog/appyters/Roadmap_Epigenomics_Harmonizome_ETL/appyter.json
{
  "$schema": "https://raw.githubusercontent.com/MaayanLab/appyter-catalog/master/schema/appyter-validator.json",
  "name": "Roadmap_Epigenomics_Harmonizome_ETL",
  "title": "Harmonizome ETL: Roadmap Epigenomics",
  "version": "0.1.2",
  "description": "An appyter to process data from the Roadmap Epigenomics Project for the Harmonizome.",
  "image": "ETL_Logo.png",
  "authors": [
    {
      "name": "Charles R. Dai",
      "email": "charles.r.dai@gmail.com"
    }
  ],
  "url": "https://github.com/MaayanLab/Harmonizome-Data-Processing-Appyters",
  "tags": [
    "Roadmap Epigenomics",
    "Harmonizome",
    "ETL Script"
  ],
  "license": "CC-BY-NC-SA-4.0",
  "appyter": {
    "file": "Roadmap Epigenomics.ipynb",
    "profile": "biojupies"
  }
}

=== MaayanLab/appyter-catalog/appyters/Gene_Centric_GEO_Reverse_Search/appyter.json
{
  "$schema": "https://raw.githubusercontent.com/MaayanLab/appyter-catalog/master/schema/appyter-validator.json",
  "name": "Gene_Centric_GEO_Reverse_Search",
  "title": "Gene Centric GEO Reverse Search",
  "version": "0.0.3",
  "description": "An appyter that generates volcano plot of gene signatures for an input gene and species of interest",
  "image": "volcano_plot_ex.png",
  "authors": [
    {
      "name": "Kerwin Chen",
      "email": "kc764@cornell.edu"
    },
    {
      "name": "Alex Lachmann",
      "email": "alexander.lachmann@mssm.edu"
    },
    {
      "name": "Sherry Xie",
      "email": "zhuorui.xie@mssm.edu"
    },
    {
      "name": "Megan Wojciechowiczl",
      "email": "megan.wojciechowicz@icahn.mssm.edu"
    },
    {
      "name": "Daniel Clarke",
      "email": "daniel.clarke@mssm.edu"
    },
    {
      "name": "Avi Ma'ayan",
      "email": "avi.maayan@mssm.edu"
    }
  ],
  "url": "https://github.com/MaayanLab/appyter-catalog/appyters/Gene_Centric_GEO_Reverse_Search",
  "tags": [
    "Signatures",
    "Volcano Plot"
  ],
  "license": "CC-BY-NC-SA-4.0",
  "public": true,
  "appyter": {
    "file": "GEO_Reverse_Search.ipynb",
    "profile": "biojupies",
    "extras": [
      "hide-code",
      "toggle-code"
    ]
  }
}

=== MaayanLab/appyter-catalog/appyters/scRNA_seq/appyter.json
{
  "$schema": "https://raw.githubusercontent.com/MaayanLab/appyter-catalog/master/schema/appyter-validator.json",
  "name": "scRNA_seq",
  "title": "Single cell RNA-seq analysis pipeline",
  "version": "0.1.1",
  "description": "scRNA-seq analysis pipeline enables users to analyze and visualize scRNA-seq datasets with state-of-the-art algorithms and visualization methods.",
  "image": "screenshot.png",
  "authors": [
    {
      "name": "Minji Jeon",
      "email": "minji.jeon1@gmail.com"
    }
  ],
  "url": "https://github.com/MaayanLab/appyter-catalog",
  "tags": [
    "RNA-seq",
    "scRNA-seq"
  ],
  "license": "CC-BY-NC-SA-4.0",
  "appyter": {
    "file": "Single_cell_RNA_seq_Analysis_Pipeline.ipynb",
    "profile": "biojupies"
  }
}

=== MaayanLab/appyter-catalog/appyters/CTD_Disease_Harmonizome_ETL/appyter.json
{
  "$schema": "https://raw.githubusercontent.com/MaayanLab/appyter-catalog/master/schema/appyter-validator.json",
  "name": "CTD_Disease_Harmonizome_ETL",
  "title": "CTD (Disease) Harmonizome ETL",
  "version": "0.0.1",
  "description": "A Data Processor for the Comparative Toxicogenomics Database",
  "authors": [
    {
      "name": "Charles R. Dai",
      "email": "charles.r.dai@gmail.com"
    }
  ],
  "url": "https://github.com/MaayanLab/Harmonizome-Data-Processing-Appyters",
  "tags": [
    "Harmonizome",
    "Harmonizome ETL Script",
    "CTD",
    "Comparative Tosicogenomics Database"
  ],
  "license": "MIT",
  "appyter": {
    "file": "CTD (Disease).ipynb",
    "profile": "biojupies"
  }
}

=== MaayanLab/appyter-catalog/appyters/MGI_Harmonizome_ETL/appyter.json
{
  "$schema": "https://raw.githubusercontent.com/MaayanLab/appyter-catalog/master/schema/appyter-validator.json",
  "name": "MGI_Harmonizome_ETL",
  "title": "MGI Harmonizome ETL",
  "version": "0.0.1",
  "description": "A Data Processor for the Mouse Gene Ontology (MGI) Dataset",
  "authors": [
    {
      "name": "Charles R. Dai",
      "email": "charles.r.dai@gmail.com"
    }
  ],
  "url": "https://github.com/MaayanLab/Harmonizome-Data-Processing-Appyters",
  "tags": [
    "Harmonizome",
    "Harmonizome ETL Script",
    "MGI",
    "Mouse Gene Ontology"
  ],
  "license": "MIT",
  "appyter": {
    "file": "MGI.ipynb",
    "profile": "biojupies"
  }
}
