=== MaayanLab/appyter-catalog/schema/appyter-validator.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "properties": {
    "$schema": {
      "description": "A reference to this schema",
      "type": "string",
      "enum": [
        "https://raw.githubusercontent.com/MaayanLab/appyter-catalog/master/schema/appyter-validator.json"
      ]
    },
    "name": {
      "description": "Slug name of this appyter (same as directory, used as url location)",
      "type": "string",
      "pattern": "^[a-zA-Z][a-zA-Z0-9_]*$"
    },
    "title": {
      "description": "Appyter title",
      "type": "string"
    },
    "version": {
      "description": "Semver version",
      "type": "string",
      "format": "regex",
      "pattern": "^[0-9]+\\.[0-9]+\\.[0-9]+$"
    },
    "description": {
      "description": "A short description of the appyter",
      "type": "string",
      "maxLength": 150
    },
    "authors": {
      "description": "A list of authors who contributed to the appyter",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "description": "The name of the author",
            "type": "string"
          },
          "email": {
            "description": "The email of the author",
            "type": "string",
            "format": "email"
          }
        }
      }
    },
    "image": {
      "description": "A relative path (preferred) or url to a thumbnail for the appyter. Size: 1280x720",
      "type": "string"
    },
    "url": {
      "description": "A url to the source code or website of the appyter",
      "type": "string",
      "format": "url"
    },
    "tags": {
      "description": "A set of tags describing the appyter",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "license": {
      "description": "A license identified by https://spdx.org/licenses/",
      "type": "string"
    },
    "public": {
      "description": "Whether or not this should be visible on the catalog (defaults to true)",
      "type": "boolean"
    },
    "appyter": {
      "description": "Appyter information and configuration",
      "type": "object",
      "properties": {
        "file": {
          "description": "The appyter file relative to this directory",
          "type": "string"
        },
        "profile": {
          "description": "The pre-made profile to base the appyter off of",
          "type": "string"
        },
        "extras": {
          "description": "Any extras to enable in your appyter",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "file"
      ]
    }
  },
  "required": [
    "$schema",
    "name",
    "title",
    "version",
    "description",
    "authors",
    "license",
    "appyter"
  ]
}

=== MaayanLab/appyter-catalog/appyters/PrismEXP/appyter.json
{
  "$schema": "https://raw.githubusercontent.com/MaayanLab/appyter-catalog/master/schema/appyter-validator.json",
  "name": "PrismEXP",
  "title": "PrismEXP Appyter",
  "version": "0.0.5",
  "description": "An appyter that calulates gene function prediction for arbitrary gene set libraries using the PrismEXP algorithm and a pretrained model.",
  "image": "featured-image.png",
  "authors": [
    {
      "name": "Alexander Lachmann",
      "email": "alexander.lachmann@mssm.edu"
    }
  ],
  "url": "https://github.com/MaayanLab/appyter-catalog",
  "tags": [
    "Machine Learning",
    "Enrichr",
    "Geneshot",
    "RNA-seq"
  ],
  "license": "CC-BY-NC-SA-4.0",
  "appyter": {
    "file": "PrismEXP.ipynb",
    "profile": "biojupies",
    "extras": [
      "toc",
      "toggle-code"
    ]
  }
}

=== MaayanLab/appyter-catalog/appyters/HPO_Harmonizome_ETL/appyter.json
{
  "$schema": "https://raw.githubusercontent.com/MaayanLab/appyter-catalog/master/schema/appyter-validator.json",
  "name": "HPO_Harmonizome_ETL",
  "title": "Harmonizome ETL: Human Phenotype Ontology",
  "version": "0.1.2",
  "description": "An appyter to process data from Human Phenotype Ontology for the Harmonizome.",
  "image": "ETL_Logo.png",
  "authors": [
    {
      "name": "Charles R. Dai",
      "email": "charles.r.dai@gmail.com"
    }
  ],
  "url": "https://github.com/MaayanLab/Harmonizome-Data-Processing-Appyters",
  "tags": [
    "Harmonizome",
    "Harmonizome ETL Script",
    "Human Phenotype Ontology"
  ],
  "license": "MIT",
  "appyter": {
    "file": "HPO.ipynb",
    "profile": "biojupies"
  }
}

=== MaayanLab/appyter-catalog/appyters/Enrichr_Canvas_Appyter/appyter.json
{
  "$schema": "https://raw.githubusercontent.com/MaayanLab/appyter-catalog/master/schema/appyter-validator.json",
  "name":"Enrichr_Canvas_Appyter",
  "title": "Enrichr Canvas Appyter",
  "version": "0.0.2",
  "description": "An appyter that creates a hexagonal canvas comparing a user-inputted gene list with gene sets in a selected Enrichr library.",
  "authors": [
    {
      "name": "Skylar Litz",
      "email": "litzskylar@gmail.com"
    },
    {
      "name": "Megan L. Wojciechowicz",
      "email": "megan.wojciechowicz@icahn.mssm.edu"
    }
  ],
  "url": "https://github.com/MaayanLab/appyter-catalog",
  "tags": [
    "Enrichr", "canvas"
  ],
  "license": "Apache-2.0",
  "appyter": {
    "file": "Enrichr-Canvas-Appyter.ipynb",
    "profile": "biojupies"
  }
}

=== MaayanLab/appyter-catalog/appyters/THPA_Immunohistochemistry_Harmonizome_ETL/appyter.json
{
  "$schema": "https://raw.githubusercontent.com/MaayanLab/appyter-catalog/master/schema/appyter-validator.json",
  "name": "THPA_Immunohistochemistry_Harmonizome_ETL",
  "title": "THPA (Immunohistochemistry) Harmonizome ETL",
  "version": "0.0.1",
  "description": "A Data Processor for The Human Protein Atlas Normal Tissue Immunihistochemistry Dataset",
  "authors": [
    {
      "name": "Charles R. Dai",
      "email": "charles.r.dai@gmail.com"
    }
  ],
  "url": "https://github.com/MaayanLab/Harmonizome-Data-Processing-Appyters",
  "tags": [
    "Harmonizome",
    "Harmonizome ETL Script",
    "THPA",
    "The Human Protein Atlas"
  ],
  "license": "MIT",
  "appyter": {
    "file": "THPA (Immunohistochemistry).ipynb",
    "profile": "biojupies"
  }
}

=== MaayanLab/appyter-catalog/appyters/tcgaDataLoader/appyter.json
{
  "$schema": "https://raw.githubusercontent.com/MaayanLab/appyter-catalog/master/schema/appyter-validator.json",
  "name": "tcgaDataLoader",
  "title": "tcgaDataLoader",
  "version": "0.0.1",
  "description": "An appyter that loads RNA-seq and clinical data tables from The Cancer Genome Atlas (TCGA) based on desired search parameters for further analysis.",
  "authors": [
    {
      "name": "Nicole Moiseyev",
      "email": "nicole.moiseyev@duke.edu"
    }
  ],
  "url": "https://github.com/MaayanLab/appyter-catalog",
  "tags": ["Databases", "TCGA"],
  "license": "MIT",
  "appyter": {
    "file": "tcgaDataLoader.ipynb",
    "profile": "biojupies"
  }
}

=== MaayanLab/appyter-catalog/appyters/Enrichr_Scatterplot_Appyter/appyter.json
{
  "$schema": "https://raw.githubusercontent.com/MaayanLab/appyter-catalog/master/schema/appyter-validator.json",
  "name": "Enrichr_Scatterplot_Appyter",
  "title": "Enrichr Scatterplot Appyter",
  "version": "0.0.6",
  "description": "An appyter that displays enrichment analysis results on a scatterplot of gene sets from an Enrichr library clustered by similarity.",
  "image": "featured-image.png",
  "authors": [
    {
      "name": "Skylar Litz",
      "email": "litzskylar@gmail.com"
    }
  ],
  "url": "https://github.com/MaayanLab/appyter-catalog",
  "tags": [
    "Enrichr",
    "Enrichment Analysis"
  ],
  "license": "CC-BY-NC-SA-4.0",
  "appyter": {
    "file": "Scatter-Appyter.ipynb",
    "profile": "biojupies",
    "extras": [
      "toc",
      "toggle-code"
    ]
  }
}

=== MaayanLab/appyter-catalog/appyters/ChEA3_Appyter/appyter.json
{
  "$schema": "https://raw.githubusercontent.com/MaayanLab/appyter-catalog/master/schema/appyter-validator.json",
  "name": "ChEA3_Appyter",
  "title": "ChEA3 Appyter",
  "version": "0.0.1",
  "description": "ChIP-X Enrichment Analysis 3 Appyter",
  "image": "chea3_appyter_logo.png",
  "authors": [
    {
      "name": "Alex Tsai",
      "email": "atsai3720@gmail.com"
    }
  ],
  "url": "https://github.com/MaayanLab/appyter-catalog",
  "tags": [
    "ChEA3",
    "Enrichment Analysis"
  ],
  "license": "CC-BY-NC-SA-4.0",
  "public": true,
  "appyter": {
    "file": "ChEA3_Appyter.ipynb",
    "profile": "biojupies",
    "extras": [
      "toc",
      "hide-code",
      "toggle-code"
    ]
  }
}

=== MaayanLab/appyter-catalog/appyters/CORUM_Harmonizome_ETL/appyter.json
{
  "$schema": "https://raw.githubusercontent.com/MaayanLab/appyter-catalog/master/schema/appyter-validator.json",
  "name": "CORUM_Harmonizome_ETL",
  "title": "CORUM Harmonizome ETL",
  "version": "0.0.1",
  "description": "A Data Processor for the CORUM Database",
  "authors": [
    {
      "name": "Charles R. Dai",
      "email": "charles.r.dai@gmail.com"
    }
  ],
  "url": "https://github.com/MaayanLab/Harmonizome-Data-Processing-Appyters",
  "tags": [
    "Harmonizome",
    "Harmonizome ETL Script",
    "CORUM"
  ],
  "license": "MIT",
  "appyter": {
    "file": "CORUM.ipynb",
    "profile": "biojupies"
  }
}
