=== MaayanLab/appyter-catalog/schema/appyter-validator.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "properties": {
    "$schema": {
      "description": "A reference to this schema",
      "type": "string",
      "enum": [
        "https://raw.githubusercontent.com/MaayanLab/appyter-catalog/master/schema/appyter-validator.json"
      ]
    },
    "name": {
      "description": "Slug name of this appyter (same as directory, used as url location)",
      "type": "string",
      "pattern": "^[a-zA-Z][a-zA-Z0-9_]*$"
    },
    "title": {
      "description": "Appyter title",
      "type": "string"
    },
    "version": {
      "description": "Semver version",
      "type": "string",
      "format": "regex",
      "pattern": "^[0-9]+\\.[0-9]+\\.[0-9]+$"
    },
    "description": {
      "description": "A short description of the appyter",
      "type": "string",
      "maxLength": 150
    },
    "authors": {
      "description": "A list of authors who contributed to the appyter",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "description": "The name of the author",
            "type": "string"
          },
          "email": {
            "description": "The email of the author",
            "type": "string",
            "format": "email"
          }
        }
      }
    },
    "image": {
      "description": "A relative path (preferred) or url to a thumbnail for the appyter. Size: 1280x720",
      "type": "string"
    },
    "url": {
      "description": "A url to the source code or website of the appyter",
      "type": "string",
      "format": "url"
    },
    "tags": {
      "description": "A set of tags describing the appyter",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "license": {
      "description": "A license identified by https://spdx.org/licenses/",
      "type": "string"
    },
    "public": {
      "description": "Whether or not this should be visible on the catalog (defaults to true)",
      "type": "boolean"
    },
    "appyter": {
      "description": "Appyter information and configuration",
      "type": "object",
      "properties": {
        "file": {
          "description": "The appyter file relative to this directory",
          "type": "string"
        },
        "profile": {
          "description": "The pre-made profile to base the appyter off of",
          "type": "string"
        },
        "extras": {
          "description": "Any extras to enable in your appyter",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "file"
      ]
    }
  },
  "required": [
    "$schema",
    "name",
    "title",
    "version",
    "description",
    "authors",
    "license",
    "appyter"
  ]
}

=== MaayanLab/appyter-catalog/appyters/Gene_Expression_T2D_Signatures/appyter.json
{
    "$schema": "https://raw.githubusercontent.com/MaayanLab/appyter-catalog/master/schema/appyter-validator.json",
    "name": "Gene_Expression_T2D_Signatures",
    "title": "My Gene's Expression in T2D Transcriptomics Signatures",
    "version": "0.0.4",
    "description": "An appyter that generates volcano plots for visualizing gene-specific expression in Type 2 Diabetes signatures.",
    "image": "example_plot.png",
    "authors": [
      {
        "name": "Sherry Xie",
        "email": "sxie04@gmail.com"
      },
      {
        "name": "Alex Lachmann",
        "email": "alexander.lachmann@mssm.edu"
      },
      {
        "name": "Kathleen Jagodnik",
        "email": "kmjagodnik@gmail.com"
      },
      {
        "name": "Mark Keller",
        "email": "mark.keller@wisc.edu"
      }
    ],
    "url": "https://github.com/MaayanLab/appyter-catalog/tree/master/appyters/Gene_Expression_T2D_Signatures",
    "tags": [
      "Type 2 Diabetes",
      "T2D",
      "Signatures",
      "Transcriptomics",
      "Volcano Plot",
      "Visualization"
    ],
    "license": "CC-BY-NC-SA-4.0",
    "appyter": {
      "file": "Gene_Expression_T2D_Signatures.ipynb",
      "profile": "biojupies",
      "extras": [
        "hide-code",
        "toggle-code"
      ]
    }
  }

=== MaayanLab/appyter-catalog/appyters/Gene_Network_Analysis/appyter.json
{
  "$schema": "https://raw.githubusercontent.com/MaayanLab/appyter-catalog/master/schema/appyter-validator.json",
  "name": "Gene_Network_Analysis",
  "title": "Gene Network Analysis",
  "version": "0.0.0",
  "description": "An appyter for the analysis of gene network clusters using various algorithms.",
  "authors": [
    {
      "name": "Nicole Moiseyev",
      "email": "nicole.moiseyev@duke.edu"
    }
  ],
  "url": "https://github.com/MaayanLab/appyter-catalog",
  "tags": ["Enrichment Analysis", "Genes", "Clsutering", "Enrichr"],
  "license": "MIT",
  "appyter": {
    "file": "Gene_Network_Analysis.ipynb",
    "profile": "biojupies"
  }
}

=== MaayanLab/appyter-catalog/appyters/KEA3_Appyter/appyter.json
{
  "$schema": "https://raw.githubusercontent.com/MaayanLab/appyter-catalog/master/schema/appyter-validator.json",
  "name": "KEA3_Appyter",
  "title": "KEA3 Appyter",
  "version": "1.0.1",
  "description": "An appyter that retrieves and displays KEA3 results.",
  "image": "KEA3_Screenshot.png",
  "authors": [
    {
      "name": "Serena Zhang",
      "email": "serena19@sas.upenn.edu"
    },
    {
      "name": "Maxim Kuleshov",
      "email": "kuleshov.max.v@gmail.com"
    }
  ],
  "url": "https://github.com/MaayanLab/appyter-catalog",
  "tags": [
    "KEA3",
    "Kinase Enrichment Analysis",
    "Kinome"
  ],
  "license": "CC-BY-NC-SA-4.0",
  "appyter": {
    "file": "KEA3-Appyter.ipynb",
    "profile": "biojupies",
    "extras": [
      "toc",
      "toggle-code"
    ]
  }
}

=== MaayanLab/appyter-catalog/appyters/GeneRIF_Harmonizome_ETL/appyter.json
{
  "$schema": "https://raw.githubusercontent.com/MaayanLab/appyter-catalog/master/schema/appyter-validator.json",
  "name": "GeneRIF_Harmonizome_ETL",
  "title": "GeneRIF Harmonizome ETL",
  "version": "0.0.1",
  "description": "A Data Processor for the GeneRIF Dataset",
  "authors": [
    {
      "name": "Charles R. Dai",
      "email": "charles.r.dai@gmail.com"
    }
  ],
  "url": "https://github.com/MaayanLab/Harmonizome-Data-Processing-Appyters",
  "tags": [
    "Harmonizome",
    "Harmonizome ETL Script",
    "GeneRIF"
  ],
  "license": "MIT",
  "appyter": {
    "file": "GeneRIF.ipynb",
    "profile": "biojupies"
  }
}

=== MaayanLab/appyter-catalog/appyters/Drugmonizome-ML/appyter.json
{
  "$schema": "https://raw.githubusercontent.com/MaayanLab/appyter-catalog/master/schema/appyter-validator.json",
  "name": "Drugmonizome-ML",
  "title": "Drugmonizome-ML",
  "version": "0.0.1",
  "description": "Machine learning pipeline to predict drug screen hits from small molecule attributes",
  "authors": [
    {
      "name": "Daniel Stein",
      "email": "djs31415@gmail.com"
    }
  ],
  "url": "https://github.com/MaayanLab/appyter-catalog",
  "tags": [
    "drugs", "small molecules", "drug set libraries", "Drugmonizome", "drug screen"
  ],
  "license": "Apache-2.0",
  "appyter": {
    "file": "Drugmonizome-ML.ipynb",
    "profile": "biojupies"
  }
}

=== MaayanLab/appyter-catalog/appyters/CFDE-Gene-WG/appyter.json
{
  "$schema": "https://raw.githubusercontent.com/MaayanLab/appyter-catalog/master/schema/appyter-validator.json",
  "name": "CFDE-Gene-WG",
  "title": "CFDE Gene-WG",
  "version": "0.0.13",
  "description": "This Appyter uses FAIR APIs from different DCCs to find and present gene-centric knowledge.",
  "image": "",
  "public": false,
  "authors": [
    {
      "name": "Daniel Clarke",
      "email": "danieljbclarkemssm@gmail.com"
    }
  ],
  "url": "https://github.com/MaayanLab/appyter-catalog",
  "tags": [
    "Gene"
  ],
  "license": "CC-BY-NC-SA-4.0",
  "appyter": {
    "file": "GeneWG.ipynb",
    "profile": "biojupies",
    "extras": [
      "toc",
      "toggle-code",
      "hide-code"
    ]
  }
}

=== MaayanLab/appyter-catalog/appyters/Pathway_Commons_Harmonizome_ETL/appyter.json
{
  "$schema": "https://raw.githubusercontent.com/MaayanLab/appyter-catalog/master/schema/appyter-validator.json",
  "name": "Pathway_Commons_Harmonizome_ETL",
  "title": "Harmonizome ETL: Pathway Commons",
  "version": "0.1.3",
  "description": "An appyter to process data from Pathway Commons for the Harmonizome.",
  "image": "ETL_Logo.png",
  "authors": [
    {
      "name": "Charles R. Dai",
      "email": "charles.r.dai@gmail.com"
    }
  ],
  "url": "https://github.com/MaayanLab/Harmonizome-Data-Processing-Appyters",
  "tags": [
    "Pathway Commons",
    "Harmonizome",
    "ETL Script"
  ],
  "license": "CC-BY-NC-SA-4.0",
  "appyter": {
    "file": "Pathway Commons.ipynb",
    "profile": "biojupies"
  }
}

=== MaayanLab/appyter-catalog/appyters/BioGPS_Harmonizome_ETL/appyter.json
{
  "$schema": "https://raw.githubusercontent.com/MaayanLab/appyter-catalog/master/schema/appyter-validator.json",
  "name": "BioGPS_Harmonizome_ETL",
  "title": "BioGPS Harmonizome ETL",
  "version": "0.0.1",
  "description": "A Data Processor for the BioGPS Datasets",
  "authors": [
    {
      "name": "Charles R. Dai",
      "email": "charles.r.dai@gmail.com"
    }
  ],
  "url": "https://github.com/MaayanLab/Harmonizome-Data-Processing-Appyters",
  "tags": [
    "Harmonizome",
    "Harmonizome ETL Script",
    "BioGPS"
  ],
  "license": "MIT",
  "appyter": {
    "file": "BioGPS.ipynb",
    "profile": "biojupies"
  }
}
