=== MaayanLab/appyter-catalog/schema/template-validator.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "properties": {
    "$schema": {
      "description": "A reference to this schema",
      "type": "string",
      "enum": [
        "https://raw.githubusercontent.com/MaayanLab/jupyter-template-catalog/master/schema/template-validator.json"
      ]
    },
    "name": {
      "description": "Slug name of this template (same as directory, used as url location)",
      "type": "string",
      "pattern": "^[a-zA-Z][a-zA-Z0-9_]*$"
    },
    "title": {
      "description": "Template title",
      "type": "string"
    },
    "version": {
      "description": "Semver version",
      "type": "string",
      "format": "regex",
      "pattern": "^[0-9]+\\.[0-9]+\\.[0-9]+$"
    },
    "description": {
      "description": "A short description of the template",
      "type": "string",
      "maxLength": 150
    },
    "authors": {
      "description": "A list of authors who contributed to the template",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "description": "The name of the author",
            "type": "string"
          },
          "email": {
            "description": "The email of the author",
            "type": "string",
            "format": "email"
          }
        }
      }
    },
    "url": {
      "description": "A url to the source code or website of the template",
      "type": "string",
      "format": "url"
    },
    "tags": {
      "description": "A set of tags describing the template",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "license": {
      "description": "A license identified by https://spdx.org/licenses/",
      "type": "string"
    },
    "template": {
      "description": "Template information and configuration",
      "type": "object",
      "properties": {
        "file": {
          "description": "The template file relative to this directory",
          "type": "string"
        },
        "profile": {
          "description": "The jupyter-template pre-made profile to base the template off of",
          "type": "string"
        }
      },
      "required": [
        "file",
        "profile"
      ]
    }
  },
  "required": [
    "$schema",
    "name",
    "title",
    "version",
    "description",
    "authors",
    "license",
    "template"
  ]
}

=== MaayanLab/appyter-catalog/templates/scEnrichr/template.json
{
  "$schema": "https://raw.githubusercontent.com/MaayanLab/jupyter-template-catalog/master/schema/template-validator.json",
  "name": "scEnrichr",
  "title": "scEnrichr",
  "version": "0.0.1",
  "description": "An Enrichr interface for single cell data",
  "authors": [
    {
      "name": "Daniel J. B. Clarke",
      "email": "u8sand@gmail.com"
    }
  ],
  "url": "https://github.com/maayanLab/scEnrichr",
  "tags": [
    "Enrichment Analysis",
    "RNA-seq",
    "scRNA-seq"
  ],
  "license": "Apache-2.0",
  "template": {
    "file": "scEnrichr.ipynb",
    "profile": "biojupies"
  }
}

=== MaayanLab/appyter-catalog/templates/SC_RNA_seq/template.json
{
  "$schema": "https://raw.githubusercontent.com/MaayanLab/jupyter-template-catalog/master/schema/template-validator.json",
  "name": "SC_RNA_seq",
  "title": "Single cell RNA-seq analysis pipeline",
  "version": "0.0.1",
  "description": "scRNA-seq analysis pipeline enables users to analyze and visualize scRNA-seq datasets with state-of-the-art algorithms and visualization methods.",
  "authors": [
    {
      "name": "Minji Jeon",
      "email": "minji.jeon1@gmail.com"
    }
  ],
  "url": "https://github.com/MaayanLab/jupyter-template-catalog",
  "tags": [
    "SC_RNA_seq"
  ],
  "license": "Apache-2.0",
  "template": {
    "file": "Single_cell_RNA_seq_Analysis_Pipeline_Template.ipynb",
    "profile": "biojupies"
  }
}

=== MaayanLab/appyter-catalog/templates/Enrichr_compressed_bar_chart_figure/template.json
{
  "$schema": "https://raw.githubusercontent.com/MaayanLab/jupyter-template-catalog/master/schema/template-validator.json",
  "name":"Enrichr_compressed_bar_chart_figure",
  "title": "Enrichr Compressed Bar Chart Figure",
  "version": "0.0.1",
  "description": "A template that turns gene set enrichment analysis results from Enrichr into a publishable figure.",
  "authors": [
    {
      "name": "Megan L. Wojciechowicz",
      "email": "megan.wojciechowicz@icahn.mssm.edu"
    }
  ],
  "url": "https://github.com/MaayanLab/jupyter-template-catalog",
  "tags": [
    "Enrichment Analysis"
  ],
  "license": "Apache-2.0",
  "template": {
    "file": "Enrichr_compressed_bar_chart_figure.ipynb",
    "profile": "biojupies"
  }
}

=== MaayanLab/appyter-catalog/templates/Bulk_RNA_seq/template.json
{
  "$schema": "https://raw.githubusercontent.com/MaayanLab/jupyter-template-catalog/master/schema/template-validator.json",
  "name": "Bulk_RNA_seq",
  "title": "Bulk RNA-seq analysis pipeline",
  "version": "0.0.1",
  "description": "Bulk RNA-seq analysis pipeline enables you to analyze and visualize datasets with state-of-the-art algorithms and visualization methods.",
  "authors": [
    {
      "name": "Minji Jeon",
      "email": "minji.jeon1@gmail.com"
    }
  ],
  "url": "https://github.com/MaayanLab/jupyter-template-catalog",
  "tags": [
    "RNAseq"
  ],
  "license": "Apache-2.0",
  "template": {
    "file": "RNA_seq_Analysis_Pipeline_Template.ipynb",
    "profile": "biojupies"
  }
}

=== MaayanLab/appyter-catalog/templates/Enrichr_figure/template.json
{
  "$schema": "https://raw.githubusercontent.com/MaayanLab/jupyter-template-catalog/master/schema/template-validator.json",
  "name": "enrichr_figure",
  "title": "Enrichr Figure",
  "version": "0.0.1",
  "description": "A jupyter template that turns gene set enrichment analysis results from Enrichr into a publishable figure.",
  "authors": [
    {
      "name": "Megan L. Wojciechowicz",
      "email": "megan.wojciechowicz@icahn.mssm.edu"
    }
  ],
  "url": "https://github.com/MaayanLab/jupyter-template-catalog",
  "tags": [
    "Enrichment Analysis"
  ],
  "license": "Apache-2.0",
  "template": {
    "file": "Enrichr_figure.ipynb",
    "profile": "biojupies"
  }
}
